[project]
name = 'edito-python-stac'
version = "0.1.0"
description = 'using STAC with python, edito STAC and other STAC catalogs'
license = {text = "MIT"}
readme = "READme.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "aiohttp>=3.11.13",
    "cartopy>=0.24.1",
    "copernicusmarine>=2.0.1",
    "geopandas>=1.0.1",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "pystac-client>=0.8.6",
    "requests>=2.32.3",
    "shapely>=2.0.7",
    "xarray>=2025.1.2",
]


